### AIM

Implement Python programming constructs and libraries such as NumPy and Pandas for basic data analysis tasks.
(array, zeros, ones, shape, reshape, read_csv, dataframe, head, tail, info, describe, dtypes)

In [2]:
import numpy as np
import pandas as pd

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
zeros_arr = np.zeros((3, 3))
ones_arr = np.ones((2, 4))

print("Zeros array:\n", zeros_arr)
print("Ones array:\n", ones_arr)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
print("Shape of ones_arr:", ones_arr.shape)


Shape of ones_arr: (2, 4)


In [6]:
reshaped = arr.reshape(5, 1)
print("Reshaped array:\n", reshaped)


Reshaped array:
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [7]:
df = pd.read_csv("datasets/thyroid.csv")


In [8]:
df.head(2)




Age Gender Smoking Hx Smoking Hx Radiothreapy Thyroid Function  \
0   27      F      No         No              No        Euthyroid   
1   34      F      No        Yes              No        Euthyroid   

         Physical Examination Adenopathy       Pathology   Focality Risk    T  \
0  Single nodular goiter-left         No  Micropapillary  Uni-Focal  Low  T1a   
1         Multinodular goiter         No  Micropapillary  Uni-Focal  Low  T1a   

    N   M Stage       Response Recurred  
0  N0  M0     I  Indeterminate       No  
1  N0  M0     I      Excellent       No

In [9]:
df.tail(2)


Age Gender Smoking Hx Smoking Hx Radiothreapy          Thyroid Function  \
381   61      M     Yes        Yes             Yes  Clinical Hyperthyroidism   
382   67      M     Yes         No              No                 Euthyroid   

    Physical Examination Adenopathy     Pathology     Focality  Risk    T  \
381  Multinodular goiter  Extensive  Hurthel cell  Multi-Focal  High  T4b   
382  Multinodular goiter  Bilateral     Papillary  Multi-Focal  High  T4b   

       N   M Stage               Response Recurred  
381  N1b  M0   IVA  Structural Incomplete      Yes  
382  N1b  M0   IVA  Structural Incomplete      Yes

In [10]:
df.info()


<class 'pandas.DataFrame'>
RangeIndex: 383 entries, 0 to 382
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   383 non-null    int64
 1   Gender                383 non-null    str  
 2   Smoking               383 non-null    str  
 3   Hx Smoking            383 non-null    str  
 4   Hx Radiothreapy       383 non-null    str  
 5   Thyroid Function      383 non-null    str  
 6   Physical Examination  383 non-null    str  
 7   Adenopathy            383 non-null    str  
 8   Pathology             383 non-null    str  
 9   Focality              383 non-null    str  
 10  Risk                  383 non-null    str  
 11  T                     383 non-null    str  
 12  N                     383 non-null    str  
 13  M                     383 non-null    str  
 14  Stage                 383 non-null    str  
 15  Response              383 non-null    str  
 16  Recurred           

In [11]:
df.describe()


Age
count  383.000000
mean    40.866841
std     15.134494
min     15.000000
25%     29.000000
50%     37.000000
75%     51.000000
max     82.000000

In [12]:
df.dtypes


Age                     int64
Gender                    str
Smoking                   str
Hx Smoking                str
Hx Radiothreapy           str
Thyroid Function          str
Physical Examination      str
Adenopathy                str
Pathology                 str
Focality                  str
Risk                      str
T                         str
N                         str
M                         str
Stage                     str
Response                  str
Recurred                  str
dtype: object

In [13]:
age_array = df["Age"].to_numpy()
print(age_array)


[27 34 30 62 62 52 41 46 51 40 75 59 49 50 76 42 40 44 43 52 41 44 36 70
 60 33 43 26 41 37 37 30 36 55 52 37 31 43 40 34 51 45 20 38 38 33 31 31
 26 29 43 30 25 27 25 21 43 23 23 43 24 35 54 54 22 38 35 51 22 51 40 69
 31 29 30 28 22 29 35 50 27 17 27 40 33 25 73 36 35 31 18 62 62 39 37 26
 31 24 57 28 44 42 27 51 33 42 26 24 60 60 31 66 44 32 26 37 33 23 47 28
 37 26 28 28 44 31 27 56 63 24 30 31 32 28 51 20 21 32 26 42 28 41 42 49
 29 29 25 41 33 27 50 19 35 63 24 36 31 24 33 24 28 22 27 28 29 40 31 55
 21 40 38 21 31 30 50 34 45 52 38 67 72 45 45 26 67 56 30 34 50 42 35 23
 44 23 26 61 22 31 68 57 27 25 20 33 36 36 40 17 24 38 28 36 50 51 55 31
 33 28 48 40 29 20 35 56 20 62 17 21 20 40 38 21 31 34 60 60 62 36 29 33
 75 62 56 52 35 34 32 27 52 46 30 32 25 38 31 37 21 34 30 48 31 52 38 41
 41 70 19 41 32 35 39 45 46 45 28 31 81 41 56 47 37 32 53 30 34 62 58 55
 21 27 46 44 29 26 42 56 51 61 42 34 67 63 67 73 26 30 36 31 40 49 38 27
 27 33 32 29 37 48 30 33 80 62 63 60 79 65 35 58 34